aca_health:
  target: ci
  outputs:
    ci:
      type: postgres
      host: localhost
  user: dummy
  password: dummy
  port: 5432
  dbname: aca_health
  schema: staging
  threads: 1
  keepalives_idle: 0
