version: 2

# Staging layer tests & documentation.
# Each stg_* model is a 1:1 cleaned projection of a raw ingest table.
# Goal: enforce minimal data quality before building dimensions & facts.

models:
  # the name field corresponds to the raw source table
  - name: stg_members
    # description field is a brief explanation of the model's purpose and contents
    description: "Cleaned and standardized member demographics, enrollment attributes, and behavioral metrics. Provides 1:1 transformation from staging.members_raw with proper data types, renamed columns, and basic data quality validations. Includes risk adjustment scores, engagement metrics, and geographic classifications."
    columns:
      - name: member_id
        description: "Natural member identifier from raw source."
        tests: [not_null, unique]
      - name: first_name
        description: "Member given name (raw first_name)."
      - name: last_name
        description: "Member family name (raw last_name)."
      - name: date_of_birth
        description: "Date of birth (raw dob)."
      - name: gender
        description: "Gender code (M/F/etc)."
      - name: email
        description: "Contact email address."
      - name: phone
        description: "Contact phone number."
      - name: street
        description: "Street address."
      - name: city
        description: "City."
      - name: state
        description: "State code (2-char)."
      - name: zip
        description: "Postal code."
      - name: fpl_ratio
        description: "Income / Federal Poverty Level ratio."
      - name: hios_id
        description: "HIOS identifier (if provided)."
      - name: plan_network_access_type
        description: "Plan network access type at snapshot."
      - name: plan_metal
        description: "Plan metal tier from member record."
      - name: age_group
        description: "Derived age group bucket."
      - name: region
        description: "Geographic region grouping."
      - name: enrollment_length_continuous
        description: "Approx continuous enrollment months within year."
      - name: clinical_segment
        description: "Simulated clinical segment grouping."
      - name: general_agency_name
        description: "General agency associated with member."
      - name: broker_name
        description: "Broker associated with member."
      - name: sa_contracting_entity_name
        description: "Contracting entity name."
      - name: call_count
        description: "Number of calls placed by member in year/month context."
      - name: app_login_count
        description: "Number of mobile app logins."
      - name: web_login_count
        description: "Number of web portal logins."
      - name: new_member_in_period
        description: "Flag (1/0) first-year member."
      - name: member_used_app
        description: "Flag (1/0) used mobile app."
      - name: member_had_web_login
        description: "Flag (1/0) web portal login."
      - name: member_visited_new_provider_ind
        description: "Flag (1/0) visited new provider."
      - name: high_cost_member
        description: "Flag (1/0) simulated high cost member."
      - name: mutually_exclusive_hcc_condition
        description: "Chronic condition bucket (simulated)."
      - name: geographic_reporting
        description: "Geographic reporting group."
      - name: wisconsin_area_deprivation_index
        description: "ADI decile (1-10), 10 is most deprived."
      - name: year
        description: "Reference year for enrichment attributes."
      - name: load_id
        description: "FK to staging.load_batches (ingestion batch)."
      - name: load_timestamp
        description: "Ingestion timestamp from raw table."
  - name: stg_claims
    description: "Comprehensive medical, pharmacy, and dental claims data with enhanced categorization and coding. Provides 1:1 transformation from staging.claims_raw with standardized naming, proper data types, and extensive enrichment attributes including MS-DRG codes, CPT classifications, drug information, and CCSR clinical categories."
    columns:
      - name: claim_id
        description: "Synthetic claim identifier."
        tests: [not_null, unique]
      - name: member_id
        description: "Foreign key to member (not enforced at raw layer)."
        tests:
          - relationships:
              arguments:
                to: ref('stg_members')
                field: member_id
      - name: provider_id
        description: "Provider identifier referenced on claim."
      - name: plan_id
        description: "Plan identifier at time of claim."
      - name: claim_date
        description: "Service date of claim (from service_date)."
      - name: claim_amount
        description: "Billed claim amount."
      - name: allowed_amount
        description: "Allowed amount after adjudication."
      - name: paid_amount
        description: "Paid amount (0 if denied/pending)."
      - name: claim_status
        description: "Claim status approved/denied/pending."
      - name: diagnosis_code
        description: "ICD-11 diagnosis code."
      - name: procedure_code
        description: "CPT procedure code."
      - name: charges
        description: "Billed charges amount (for metric derivations)."
      - name: allowed
        description: "Allowed amount field used by metrics."
      - name: clean_claim_status
        description: "Normalized claim status (PAID/DENIED/PENDING)."
      - name: claim_from
        description: "Claim service start date (from generator)."
      - name: clean_claim_out
        description: "Claim paid date when paid; null otherwise."
      - name: utilization
        description: "Utilization count primitive (sum to get utilization)."
      - name: hcg_units_days
        description: "Units or days count primitive (sum for units_days)."
      - name: claim_type
        description: "Facility/Professional/RX."
      - name: major_service_category
        description: "HCG major service category (toy mapping)."
      - name: provider_specialty
        description: "Rendering provider specialty (Pharmacy for RX)."
      - name: detailed_service_category
        description: "Detailed service category label."
      - name: ms_drg
        description: "MS-DRG code."
      - name: ms_drg_description
        description: "MS-DRG description."
      - name: ms_drg_mdc
        description: "MDC code for DRG."
      - name: ms_drg_mdc_desc
        description: "MDC description for DRG."
      - name: cpt
        description: "CPT code duplicate for descriptor convenience."
      - name: cpt_consumer_description
        description: "Consumer-friendly CPT description."
      - name: procedure_level_1
        description: "CPT hierarchy level 1."
      - name: procedure_level_2
        description: "CPT hierarchy level 2."
      - name: procedure_level_3
        description: "CPT hierarchy level 3."
      - name: procedure_level_4
        description: "CPT hierarchy level 4."
      - name: procedure_level_5
        description: "CPT hierarchy level 5."
      - name: channel
        description: "Place of service channel (IP/OP/SNF/URG/etc.)."
      - name: drug_name
        description: "Drug name (RX only)."
      - name: drug_class
        description: "Drug therapeutic class (GPI-4 like)."
      - name: drug_subclass
        description: "Drug therapeutic subclass (GPI-6 like)."
      - name: drug
        description: "Drug (GPI-8 like)."
      - name: is_oon
        description: "Out-of-network flag (1/0)."
      - name: best_contracting_entity_name
        description: "Provider contracting entity name."
      - name: provider_group_name
        description: "Provider group name."
      - name: ccsr_system_description
        description: "CCSR body system description."
      - name: ccsr_description
        description: "CCSR code & description."
      - name: load_id
        description: "FK to staging.load_batches."
      - name: load_timestamp
        description: "Ingestion timestamp from raw claims."
  - name: stg_plans
    description: "Health insurance plan catalog with benefit design details. Contains plan identifiers, metal tier classifications, premium structures, deductibles, out-of-pocket maximums, copay amounts, and coinsurance rates. Each row represents a unique plan-year combination."
    columns:
      - name: plan_id
        description: "Plan natural key (PLN####)."
        tests: [not_null]
      - name: plan_name
        description: "Plan marketing name."
      - name: metal_tier
        description: "ACA metal tier Bronze/Silver/Gold/Platinum."
      - name: monthly_premium
        description: "Monthly premium amount."
      - name: deductible
        description: "Annual deductible."
      - name: oop_max
        description: "Out-of-pocket maximum."
      - name: coinsurance_rate
        description: "Member coinsurance fraction (0-1)."
      - name: pcp_copay
        description: "Primary care visit copay."
      - name: effective_year
        description: "Plan effective year."
      - name: load_id
        description: "FK to staging.load_batches."
      - name: load_timestamp
        description: "Ingestion timestamp."
  - name: stg_providers
    description: "Healthcare provider directory with practice information. Includes provider identifiers, simulated NPI numbers, demographic details, medical specialties, and complete practice addresses. Represents individual practitioners and healthcare facilities in the network."
    columns:
      - name: provider_id
        description: "Provider natural key (PRV#####)."
        tests: [not_null]
      - name: npi
        description: "Fake NPI-like number."
      - name: provider_name
        description: "Provider full name (raw name)."
      - name: specialty
        description: "Medical specialty."
      - name: street
        description: "Street address."
      - name: city
        description: "City."
      - name: state
        description: "State code (2-char)."
      - name: zip
        description: "Postal code."
      - name: phone
        description: "Contact phone number."
      - name: load_id
        description: "FK to staging.load_batches."
      - name: load_timestamp
        description: "Ingestion timestamp."
  - name: stg_enrollments
    description: "Member plan enrollment periods with coverage duration metrics. Tracks continuous enrollment spans between members and plans, including start/end dates, premium payments, CSR variant assignments, and calculated coverage days. Critical for membership analytics and premium revenue tracking."
    columns:
      - name: enrollment_id
        description: "Natural enrollment identifier."
        tests: [not_null, unique]
      - name: member_id
        description: "Member foreign key reference."
        tests:
          - relationships:
              arguments:
                to: ref('stg_members')
                field: member_id
      - name: plan_id
        description: "Plan foreign key reference."
        tests:
          - relationships:
              arguments:
                to: ref('stg_plans')
                field: plan_id
      - name: start_date
        description: "Coverage start date."
      - name: end_date
        description: "Coverage end date (capped to year)."
      - name: coverage_days
        description: "Derived number of coverage days in period."
      - name: premium_paid
        description: "Premium paid by member."
      - name: csr_variant
        description: "Cost-sharing reduction variant code."
      - name: load_id
        description: "FK to staging.load_batches."
      - name: load_timestamp
        description: "Ingestion timestamp."

