version: 2

models:
  - name: agg_provider_performance
    description: "Provider performance analytics cube aggregating claims volume, financial metrics, and approval rates by provider. Supports network management, provider scorecards, and contracting decisions through provider-specific KPIs and volume categorization."
    columns:
      - name: provider_id
        description: "Provider identifier"
        tests:
          - not_null
          - unique
      - name: total_claims
        description: "Total claims handled by provider"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10000
      - name: approval_rate
        description: "Provider approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0
      - name: volume_category
        description: "Provider volume category"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['Very Low Volume', 'Low Volume', 'Moderate Volume', 'High Volume']

  - name: dashboard_summary
    description: "Executive-level KPI dashboard providing current period metrics including latest month claims volume, approval rates, high-cost member impacts, and cross-functional performance indicators. Single-row summary optimized for real-time dashboard consumption."
    columns:
      - name: report_date
        description: "Report generation date"
        tests:
          - not_null
      - name: latest_month_claims
        description: "Claims count for latest month"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100000
      - name: latest_approval_rate
        description: "Latest month approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0
      - name: high_cost_member_cost_percentage
        description: "Percentage of costs from high-cost members"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 100.0
    tests:
      - dbt_expectations.expect_table_row_count_to_equal:
          arguments:
            value: 1  # Should always be exactly one summary row

  - name: agg_plan_performance_cube
    description: "Plan performance analytics by month with standardized PMPM costs, claims approval ratios, and member engagement metrics. Critical for plan profitability analysis, pricing decisions, and competitive benchmarking across the plan portfolio."
    columns:
      - name: plan_id
        description: "Plan identifier"
        tests:
          - not_null
      - name: report_month
        description: "Month of aggregation"
        tests:
          - not_null
      - name: pmpm_paid
        description: "Paid amount per member month"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100000
      - name: approval_rate
        description: "Plan claim approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0

  # Trend cubes moved here from mart directory (definitions remain in mart/schema.yml docs if desired)
  - name: agg_trend_descriptor
    description: "{{ doc('trend_descriptor_definition') }}"
    columns:
      - name: year
        description: "Calendar year (2024 or 2025)"
        tests:
          - not_null
          - accepted_values:
              values: [2024, 2025]
      - name: is_out_of_network
        description: "Indicator (1/0) if the claim is out of network"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: clinical_segment
        description: "{{ doc('clinical_segment_values') }}"
        tests:
          - accepted_values:
              values: ["Healthy", "Chronic", "Behavioral", "Maternity", "Complex"]
      - name: high_cost_member
        description: "High cost member flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: allowed
        description: "Total allowed amount"
      - name: count_of_claims
        description: "Distinct claim count"
      - name: out_of_network_allowed
        description: "Allowed amount for out-of-network claims"
      - name: utilization
        description: "Utilization events count"
      - name: avg_days_service_to_paid
        description: "Avg days from service to paid"
  - name: agg_trend_normalizer
    description: "{{ doc('trend_norm_definition') }}"
    columns:
      - name: year
        description: "Calendar year (2024 or 2025)"
        tests:
          - not_null
          - accepted_values:
              values: [2024, 2025]
      - name: plan_metal
        description: "ACA metal tier"
        tests:
          - accepted_values:
              values: ["Bronze", "Silver", "Gold", "Platinum"]
      - name: gender
        description: "Member gender"
        tests:
          - accepted_values:
              values: ["F", "M", "O"]
      - name: clinical_segment
        description: "{{ doc('clinical_segment_values') }}"
        tests:
          - accepted_values:
              values: ["Healthy", "Chronic", "Behavioral", "Maternity", "Complex"]
      - name: new_member_in_period
        description: "New member flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: member_called_oscar
        description: "Member called flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: member_used_app
        description: "Member used app flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: high_cost_member
        description: "High cost member flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: member_months
        description: "Risk-adjusted member months"
        tests:
          - not_null
      - name: unique_members_enrolled
        description: "Distinct enrolled members"
        tests:
          - not_null
