version: 2

models:
  - name: agg_claims_monthly
    description: "Monthly claims aggregation cube"
    columns:
      - name: report_month
        description: "Month of aggregation"
        tests:
          - not_null
      - name: total_claims
        description: "Total number of claims"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100000
      - name: approval_rate
        description: "Percentage of approved claims"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0
      - name: total_paid_amount
        description: "Total amount paid"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 50000000
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          arguments:
            min_value: 1
            max_value: 24  # Max 2 years * 12 months (more realistic for test data)

  - name: agg_member_cost_cube
    description: "Member cost analysis cube with PMPM/PMPY metrics"
    columns:
      - name: member_id
        description: "Member identifier"
        tests:
          - not_null
          - unique
      - name: pmpm_cost
        description: "Per Member Per Month cost"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 5000  # Reasonable PMPM range
      - name: pmpy_cost
        description: "Per Member Per Year cost"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 60000  # Reasonable PMPY range
      - name: cost_category
        description: "Member cost risk category"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['No Claims', 'Low Cost', 'Moderate Cost', 'High Cost', 'Very High Cost']

  - name: agg_provider_performance
    description: "Provider performance analysis cube"
    columns:
      - name: provider_id
        description: "Provider identifier"
        tests:
          - not_null
          - unique
      - name: total_claims
        description: "Total claims handled by provider"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10000
      - name: approval_rate
        description: "Provider approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0
      - name: volume_category
        description: "Provider volume category"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['Very Low Volume', 'Low Volume', 'Moderate Volume', 'High Volume']

  - name: dashboard_summary
    description: "Executive KPI dashboard summary"
    columns:
      - name: report_date
        description: "Report generation date"
        tests:
          - not_null
      - name: latest_month_claims
        description: "Claims count for latest month"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100000
      - name: latest_approval_rate
        description: "Latest month approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0
      - name: high_cost_member_cost_percentage
        description: "Percentage of costs from high-cost members"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 100.0
    tests:
      - dbt_expectations.expect_table_row_count_to_equal:
          arguments:
            value: 1  # Should always be exactly one summary row

  - name: agg_plan_performance_cube
    description: "Monthly plan performance metrics with PMPM and approval ratios"
    columns:
      - name: plan_id
        description: "Plan identifier"
        tests:
          - not_null
      - name: report_month
        description: "Month of aggregation"
        tests:
          - not_null
      - name: pmpm_paid
        description: "Paid amount per member month"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100000
      - name: approval_rate
        description: "Plan claim approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0

  - name: agg_member_risk_stratification_cube
    description: "Member risk & utilization stratification cube"
    columns:
      - name: member_id
        description: "Member identifier"
        tests:
          - not_null
          - unique
      - name: paid_risk_bucket
        description: "Risk bucket based on paid amount"
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['No Cost','Low','Moderate','High','Very High']
      - name: utilization_bucket
        description: "Utilization bucket based on claim count"
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['No Util','Low Util','Moderate Util','High Util','Very High Util']

  - name: agg_provider_specialty_monthly_cube
    description: "Monthly provider specialty performance metrics"
    columns:
      - name: specialty
        description: "Provider specialty"
        tests:
          - not_null
      - name: report_month
        description: "Month of aggregation"
        tests:
          - not_null
      - name: approval_rate
        description: "Specialty approval rate"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0

  - name: agg_claims_diagnosis_summary_cube
    description: "Top 50 diagnosis codes per month with financial metrics"
    columns:
      - name: report_month
        description: "Month of aggregation"
        tests:
          - not_null
      - name: diagnosis_code
        description: "Diagnosis code"
        tests:
          - not_null
      - name: total_claims
        description: "Total claims for diagnosis in month"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100000
