version: 2

models:
  - name: dim_date
    description: "Calendar date dimension with comprehensive temporal attributes including year, quarter, month, week, and weekend indicators. Provides standard time intelligence for all fact table joins and enables temporal analysis across the data warehouse."
    columns:
      - name: date_key
        description: "Date key in YYYYMMDD format"
        tests: [not_null, unique]
      - name: full_date
        description: "Full date value"
        tests: [not_null]
      - name: year
        description: "Year"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 2000, max_value: 2030}

  - name: dim_member
    description: "Member dimension implementing SCD2 to track historical changes in member demographics, risk profiles, and engagement metrics. Maintains complete member lifecycle history with validity periods, enabling point-in-time analysis and trend tracking."
    columns:
      - name: member_id
        tests: [not_null, unique]
      - name: is_current
        tests: [not_null]

  - name: dim_plan
    description: "Plan dimension with SCD2 history tracking changes in benefit design, premium rates, and plan attributes over time. Natural key includes both plan_id and effective_year to handle annual plan updates and mid-year modifications."
    columns:
      - name: plan_id
        tests: [not_null, unique]
      - name: monthly_premium
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 50, max_value: 2000}

  - name: dim_provider
    description: "Provider dimension with SCD2 history to capture changes in provider practice details, specialties, and location information. Essential for network analysis, provider performance tracking, and geographic access studies."
    columns:
      - name: provider_id
        tests: [not_null, unique]

  - name: fct_claim
    description: "Central claims fact table containing one row per claim with foreign keys to all dimensions. Supports medical cost analysis, utilization studies, provider performance measurement, and member health outcomes tracking through comprehensive claim-level metrics."
    columns:
      - name: claim_id
        tests: [not_null, unique]
      - name: claim_amount
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 0, max_value: 100000}
      - name: member_id
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_member'), field: member_id}
      - name: provider_id
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_provider'), field: provider_id}
      - name: plan_id
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_plan'), field: plan_id}
      - name: claim_status
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments: {value_set: [approved, denied, pending]}

  - name: fct_enrollment
    description: "Enrollment fact table tracking member-plan relationships over time with coverage periods and premium information. Critical for membership analytics, revenue tracking, churn analysis, and plan performance evaluation."
    columns:
      - name: enrollment_id
        tests: [not_null, unique]
      - name: member_id
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_member'), field: member_id}
      - name: plan_id
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_plan'), field: plan_id}

  - name: star_claims
    description: "Comprehensive star schema view pre-joining claim facts with all dimensions (member, provider, plan, date) for high-performance analytics. Optimized for dashboard queries, ad-hoc analysis, and business intelligence reporting by eliminating complex joins at query time."
    columns:
      - name: claim_id
        description: "Unique identifier for the claim."
        tests: [not_null, unique]
      - name: claim_date
        description: "Date the claim was made."
        tests: [not_null]
      - name: claim_full_date
        description: "Full date value from the date dimension."
      - name: member_id
        description: "Unique identifier for the member."
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_member'), field: member_id}
      - name: member_first_name
        description: "Member's first name."
      - name: member_last_name
        description: "Member's last name."
      - name: member_dob
        description: "Member's date of birth."
      - name: member_gender
        description: "Member's gender."
      - name: member_age_group
        description: "Member's age group."
      - name: member_region
        description: "Member's region."
      - name: plan_id
        description: "Unique identifier for the plan."
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_plan'), field: plan_id}
      - name: plan_name
        description: "Name of the plan."
      - name: metal_tier
        description: "Plan's metal tier."
      - name: monthly_premium
        description: "Monthly premium for the plan."
      - name: provider_id
        description: "Unique identifier for the provider."
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_provider'), field: provider_id}
      - name: provider_name
        description: "Provider's name."
      - name: provider_specialty
        description: "Provider's specialty."
      - name: claim_amount
        description: "Total amount claimed."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 0, max_value: 100000}
      - name: allowed_amount
        description: "Allowed amount for the claim."
      - name: paid_amount
        description: "Amount paid for the claim."
      - name: claim_status
        description: "Status of the claim (approved, denied, pending)."
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments: {value_set: [approved, denied, pending]}
      - name: diagnosis_code
        description: "Diagnosis code for the claim."
      - name: procedure_code
        description: "Procedure code for the claim."
      - name: load_id
        description: "ETL load identifier."
      - name: load_timestamp
        description: "Timestamp when the record was loaded."