version: 2

models:
  - name: agg_trend_descriptor
    description: >
      Descriptor cube for trend analysis containing claim-level dimensions 
      and pre-aggregated metrics for 2024 vs 2025 comparison. This cube provides
      detailed claim breakdowns across multiple dimensions including provider specialty,
      service categories, member demographics, and geographic markets. Pre-aggregated
      metrics enable efficient PMPM calculations and trend analysis without requiring
      re-aggregation at query time.
    columns:
      - name: year
        description: "Calendar year (2024 or 2025)"
        tests: [not_null]
      - name: geographic_reporting
        description: "Oscar reporting market: OHB (Columbus), OHC (Cleveland Clinic Product), TX-HN, or state abbreviation"
      - name: claim_type
        description: "Type of claim: Facility, Professional, or RX"
      - name: major_service_category
        description: "Highest level Health Cost Guidelines (HCG) service category"
      - name: provider_specialty
        description: "Specialty of the rendering provider (or 'Pharmacy' for RX claims)"
      - name: detailed_service_category
        description: "Detailed Health Cost Guidelines (HCG) code and description"
      - name: ms_drg
        description: "Medicare Severity Diagnosis Related Group (MS-DRG) code and description"
      - name: cpt
        description: "Current Procedural Terminology (CPT) code"
      - name: channel
        description: "Place of service (e.g. IP=Inpatient, OP=Outpatient, SNF=Skilled Nursing, URG=Urgent)"
      - name: is_out_of_network
        description: "Indicator (1/0) if the claim is out of network"
      - name: clinical_segment
        description: "Member's clinical complexity segment (Healthy, Chronic, Behavioral, Maternity, Complex)"
      - name: charges
        description: "Total charges for paid claims"
      - name: denied_charges
        description: "Total charges for denied/unpaid claims"
      - name: allowed
        description: "Total allowed amount (basis for PMPM calculations)"
      - name: count_of_denied_claims
        description: "Count of distinct denied claims"
      - name: count_of_claims
        description: "Count of distinct claims"
      - name: utilization
        description: "Total utilization count"
      - name: units_days
        description: "Total units or days"
      - name: avg_days_service_to_paid
        description: "Average days from service date to payment date for paid claims"
        
  - name: agg_trend_norm
    description: >
      Normalization cube containing member-level dimensions and enrollment 
      metrics for calculating PMPM and other normalized rates. This cube provides
      the denominator (member months) for trend analysis, enabling proper normalization
      of claim costs and utilization metrics. Pre-aggregated at the member cohort level
      to align with descriptor cube dimensions.
    columns:
      - name: year
        description: "Calendar year (2024 or 2025)"
        tests: [not_null]
      - name: geographic_reporting
        description: "Oscar reporting market: OHB (Columbus), OHC (Cleveland Clinic Product), TX-HN, or state abbreviation"
      - name: plan_metal
        description: "ACA metal tier (Bronze, Silver, Gold, Platinum)"
      - name: age_group
        description: "Age group bucket for demographic analysis"
      - name: gender
        description: "Member gender"
      - name: region
        description: "Geographic region of the member"
      - name: clinical_segment
        description: "Member's clinical complexity segment (Healthy, Chronic, Behavioral, Maternity, Complex)"
      - name: enrollment_length_continuous
        description: "Continuous length of enrollment for the member (in months)"
      - name: new_member_in_period
        description: "Indicator (1/0) if member is new (enrolled for 5 months or less)"
      - name: member_called_oscar
        description: "Indicator (1/0) if member called Oscar during the period"
      - name: member_used_app
        description: "Indicator (1/0) if member used the Oscar app"
      - name: high_cost_member
        description: "Indicator (1/0) for high-cost member flag"
      - name: mutually_exclusive_hcc_condition
        description: "HHS HCC Chronic Condition Label (mutually exclusive categories)"
      - name: member_months
        description: "Total risk-adjusted member months - use as denominator for PMPM calculations"
      - name: unique_members_enrolled
        description: "Count of distinct members enrolled"

  - name: dim_date
    description: "Calendar date dimension with comprehensive temporal attributes including year, quarter, month, week, and weekend indicators. Provides standard time intelligence for all fact table joins and enables temporal analysis across the data warehouse."
    columns:
      - name: date_key
        description: "Date key in YYYYMMDD format"
        tests: [not_null, unique]
      - name: full_date
        description: "Full date value"
        tests: [not_null]
      - name: year
        description: "Year"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 2000, max_value: 2030}

  - name: dim_member
    description: "Member dimension implementing SCD2 to track historical changes in member demographics, risk profiles, and engagement metrics. Maintains complete member lifecycle history with validity periods, enabling point-in-time analysis and trend tracking."
    columns:
      - name: member_id
        description: "Natural member identifier from source system"
        tests: [not_null, unique]
      - name: first_name
        description: "Member first name (normalized to uppercase)"
      - name: last_name
        description: "Member last name (normalized to uppercase)"
      - name: date_of_birth
        description: "Member date of birth"
      - name: gender
        description: "Member gender code (M/F/O)"
      - name: age_group
        description: "Simulated age group bucket for demographic analysis"
      - name: region
        description: "Geographic region classification"
      - name: plan_metal
        description: "ACA metal tier from member enrollment (Bronze/Silver/Gold/Platinum)"
      - name: ra_mm
        description: "Risk Adjustment Member Months score"
      - name: load_id
        description: "Reference to staging load batch"
      - name: validity_start_ts
        description: "SCD2 version start timestamp (when this version became effective)"
      - name: validity_end_ts
        description: "SCD2 version end timestamp (when this version was superseded, null for current)"
      - name: is_current
        description: "Boolean flag indicating if this is the current/active version of the member record"
        tests: [not_null]

  - name: dim_plan
    description: "Plan dimension with SCD2 history tracking changes in benefit design, premium rates, and plan attributes over time. Natural key includes both plan_id and effective_year to handle annual plan updates and mid-year modifications."
    columns:
      - name: plan_id
        description: "Plan identifier from source system (PLN####)"
        tests: [not_null, unique]
      - name: plan_name
        description: "Plan marketing name (normalized to uppercase)"
      - name: metal_tier
        description: "ACA metal tier classification (Bronze/Silver/Gold/Platinum)"
      - name: monthly_premium
        description: "Monthly premium amount in dollars"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 50, max_value: 2000}
      - name: deductible
        description: "Annual deductible amount"
      - name: oop_max
        description: "Out-of-pocket maximum annual limit"
      - name: coinsurance_rate
        description: "Member coinsurance rate (decimal between 0-1)"
      - name: pcp_copay
        description: "Primary care provider copay amount"
      - name: effective_year
        description: "Plan effective year (component of natural key)"
      - name: load_id
        description: "Reference to staging load batch"
      - name: validity_start_ts
        description: "SCD2 version start timestamp"
      - name: validity_end_ts
        description: "SCD2 version end timestamp (null for current)"
      - name: is_current
        description: "Boolean flag indicating if this is the current/active version"

  - name: dim_provider
    description: "Provider dimension with SCD2 history to capture changes in provider practice details, specialties, and location information. Essential for network analysis, provider performance tracking, and geographic access studies."
    columns:
      - name: provider_id
        description: "Provider identifier from source system (PRV#####)"
        tests: [not_null, unique]
      - name: npi
        description: "Simulated National Provider Identifier"
      - name: provider_name
        description: "Provider full name (normalized to uppercase)"
      - name: specialty
        description: "Medical specialty classification"
      - name: street
        description: "Provider practice street address"
      - name: city
        description: "Provider practice city"
      - name: state
        description: "Provider practice state code"
      - name: zip
        description: "Provider practice postal code"
      - name: phone
        description: "Provider contact phone number"
      - name: load_id
        description: "Reference to staging load batch"
      - name: validity_start_ts
        description: "SCD2 version start timestamp"
      - name: validity_end_ts
        description: "SCD2 version end timestamp (null for current)"
      - name: is_current
        description: "Boolean flag indicating if this is the current/active version"

  - name: fct_claim
    description: "Central claims fact table containing one row per claim with foreign keys to all dimensions. Supports medical cost analysis, utilization studies, provider performance measurement, and member health outcomes tracking through comprehensive claim-level metrics."
    columns:
      - name: claim_id
        description: "Unique claim identifier (natural key)"
        tests: [not_null, unique]
      - name: member_id
        description: "Foreign key reference to member dimension"
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_member'), field: member_id}
      - name: provider_id
        description: "Foreign key reference to provider dimension"
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_provider'), field: provider_id}
      - name: plan_id
        description: "Foreign key reference to plan dimension"
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_plan'), field: plan_id}
      - name: claim_date
        description: "Date of service for the claim"
      - name: claim_amount
        description: "Total billed amount for the claim"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 0, max_value: 100000}
      - name: allowed_amount
        description: "Amount allowed by plan after adjudication"
      - name: paid_amount
        description: "Amount actually paid by plan"
      - name: claim_status
        description: "Processing status of the claim"
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments: {value_set: [approved, denied, pending]}
      - name: diagnosis_code
        description: "Primary diagnosis code (ICD-11)"
      - name: procedure_code
        description: "Primary procedure code (CPT)"
      - name: load_id
        description: "Reference to source staging load batch"
      - name: load_timestamp
        description: "Timestamp when record was loaded from staging"

  - name: fct_enrollment
    description: "Enrollment fact table tracking member-plan relationships over time with coverage periods and premium information. Critical for membership analytics, revenue tracking, churn analysis, and plan performance evaluation."
    columns:
      - name: enrollment_id
        description: "Unique enrollment period identifier"
        tests: [not_null, unique]
      - name: member_id
        description: "Foreign key reference to member dimension"
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_member'), field: member_id}
      - name: plan_id
        description: "Foreign key reference to plan dimension"
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_plan'), field: plan_id}
      - name: start_date
        description: "Coverage period start date"
      - name: end_date
        description: "Coverage period end date"
      - name: coverage_days
        description: "Number of days covered in enrollment period"
      - name: premium_paid
        description: "Premium amount paid by member"
      - name: csr_variant
        description: "Cost-sharing reduction variant code"
      - name: load_id
        description: "Reference to source staging load batch"
      - name: load_timestamp
        description: "Timestamp when record was loaded from staging"

  - name: star_claims
    description: "Comprehensive star schema view pre-joining claim facts with all dimensions (member, provider, plan, date) for high-performance analytics. Optimized for dashboard queries, ad-hoc analysis, and business intelligence reporting by eliminating complex joins at query time."
    columns:
      - name: claim_id
        description: "Unique identifier for the claim."
        tests: [not_null, unique]
      - name: claim_date
        description: "Date the claim was made."
        tests: [not_null]
      - name: claim_full_date
        description: "Full date value from the date dimension."
      - name: member_id
        description: "Unique identifier for the member."
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_member'), field: member_id}
      - name: member_first_name
        description: "Member's first name."
      - name: member_last_name
        description: "Member's last name."
      - name: member_dob
        description: "Member's date of birth."
      - name: member_gender
        description: "Member's gender."
      - name: member_age_group
        description: "Member's age group."
      - name: member_region
        description: "Member's region."
      - name: plan_id
        description: "Unique identifier for the plan."
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_plan'), field: plan_id}
      - name: plan_name
        description: "Name of the plan."
      - name: metal_tier
        description: "Plan's metal tier."
      - name: monthly_premium
        description: "Monthly premium for the plan."
      - name: provider_id
        description: "Unique identifier for the provider."
        tests:
          - not_null
          - relationships:
              arguments: {to: ref('dim_provider'), field: provider_id}
      - name: provider_name
        description: "Provider's name."
      - name: provider_specialty
        description: "Provider's specialty."
      - name: claim_amount
        description: "Total amount claimed."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 0, max_value: 100000}
      - name: allowed_amount
        description: "Allowed amount for the claim."
      - name: paid_amount
        description: "Amount paid for the claim."
      - name: claim_status
        description: "Status of the claim (approved, denied, pending)."
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments: {value_set: [approved, denied, pending]}
      - name: diagnosis_code
        description: "Diagnosis code for the claim."
      - name: procedure_code
        description: "Procedure code for the claim."
      - name: load_id
        description: "ETL load identifier."
      - name: load_timestamp
        description: "Timestamp when the record was loaded."