name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches: [ main, expectations, gh-pages ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: uv sync

    - name: Setup dbt profile
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml << 'EOF'
        star:
          outputs:
            dev:
              type: postgres
              host: localhost
              port: 5432
              user: dummy
              password: dummy
              dbname: dummy
              schema: public
              threads: 1
          target: dev
        EOF

    - name: Install dbt packages and generate docs
      working-directory: ./transform
      run: |
        uv run dbt deps
        uv run dbt docs generate --no-compile

    - name: Prepare docs for deployment
      run: |
        mkdir -p docs-site
        cp transform/target/index.html docs-site/
        cp transform/target/manifest.json docs-site/
        cp transform/target/catalog.json docs-site/ || true
        # Disable Jekyll processing
        touch docs-site/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        force_orphan: true
