name: Test Workflow

on:
  push:
    branches: [ main, master, gh-pages ]
  pull_request:
    branches: [ main, master, gh-pages ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Echo current directory
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        
    - name: Test basic commands
      run: |
        echo "GitHub Actions is working!"
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        date
